# Generated by Django 2.1.5 on 2019-02-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=200)),
                ('wallet_address', models.TextField()),
                ('last_update', models.DateTimeField(verbose_name='Última Atualização')),
            ],
        ),
    ]
